projects:
  vocabularAPI:
    schemaPath: Users/jonmak/Developer/My Projects/Vocabular/graphql/schema.json
    includes:
      - amplify/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: amplify/graphql
extensions:
  amplify:
    version: 3
