/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://6vs6gtf64jdfbplvdl7wfqts2m.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ki623qiznvdpfazc4lvn22emra",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9JcadIh7l",
    "aws_user_pools_web_client_id": "4nmtv7op1mjspudpno0bj05c0u",
    "oauth": {}
};


export default awsmobile;
